import { useEffect, useMemo, useState } from "react";
import { Search } from "lucide-react";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { adminVendorService } from "../../services/adminVendor.service";
import { adminProductService } from "../../services/adminProduct.service";
import { adminOrderService } from "../../services/adminOrder.service";
import { adminUserService } from "../../services/adminUser.service";
import { adminService, VendorAudit } from "../../services/admin.service";
import type { AdminProduct, AdminUser, AdminVendor, AdminOrder } from "../../types/admin";

function Empty({ text }: { text: string }) { return <div className="py-10 text-center text-sm text-muted-foreground">{text}</div>; }
export function AdminVendorsPage() {
  const [items, setItems] = useState<AdminVendor[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  useEffect(() => { adminVendorService.list().then(setItems); }, []);
  const filtered = useMemo(() => items.filter(v => (!query || `${v.shopName || v.name} ${v.ownerName}`.toLowerCase().includes(query.toLowerCase())) && (status === "all" || (v.approvalStatus || v.status || "pending").toUpperCase() === status)), [items, query, status]);
  const update = async (id: string, next: "approved" | "suspended" | "active") => { const updated = await adminVendorService.updateStatus(id, next); setItems(current => current.map(v => v.id === id ? { ...v, ...updated } : v)); };
  return <CollectionFrame title="Vendeurs" description="Validez et surveillez les boutiques de la marketplace."><Filters query={query} setQuery={setQuery} placeholder="Rechercher une boutique ou un propriétaire" /><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue placeholder="Statut" /></SelectTrigger><SelectContent>{["all", "PENDING", "APPROVED", "ACTIVE", "SUSPENDED", "REJECTED"].map(value => <SelectItem key={value} value={value}>{value === "all" ? "Tous les statuts" : value}</SelectItem>)}</SelectContent></Select><Table><TableHeader><TableRow><TableHead>Boutique</TableHead><TableHead>Propriétaire</TableHead><TableHead>Statut</TableHead><TableHead>Note</TableHead><TableHead>Produits</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(v => <TableRow key={v.id}><TableCell className="font-medium">{v.shopName || v.name}</TableCell><TableCell>{v.ownerName}</TableCell><TableCell><Badge variant="outline">{(v.approvalStatus || v.status || "pending").toUpperCase()}</Badge></TableCell><TableCell>{v.rating?.toFixed(1) || "—"}</TableCell><TableCell>{v.productCount || 0}</TableCell><TableCell className="space-x-1"><Button size="sm" onClick={() => update(v.id, "approved")}>Approuver</Button><Button size="sm" variant="outline" onClick={() => update(v.id, "active")}>Réactiver</Button><Button size="sm" variant="destructive" onClick={() => update(v.id, "suspended")}>Suspendre</Button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length && <Empty text="Aucun vendeur correspondant." />}</CollectionFrame>;
}
export function AdminProductsPage() {
  const [items, setItems] = useState<AdminProduct[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  useEffect(() => { adminProductService.list().then(setItems); }, []);
  const filtered = items.filter(p => (!query || `${p.name} ${p.vendorName} ${p.category}`.toLowerCase().includes(query.toLowerCase())) && (status === "all" || p.status === status));
  const update = async (id: string, next: "APPROVED" | "REJECTED" | "HIDDEN") => { const updated = await adminProductService.updateStatus(id, next); setItems(current => current.map(p => p.id === id ? { ...p, ...updated, status: next } : p)); };
  return <CollectionFrame title="Produits marketplace" description="Contrôlez la validation avant publication."><Filters query={query} setQuery={setQuery} placeholder="Rechercher un produit, vendeur ou catégorie" /><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue placeholder="Statut" /></SelectTrigger><SelectContent>{["all", "PENDING", "APPROVED", "REJECTED", "HIDDEN"].map(value => <SelectItem key={value} value={value}>{value === "all" ? "Tous les statuts" : value}</SelectItem>)}</SelectContent></Select><Table><TableHeader><TableRow><TableHead>Produit</TableHead><TableHead>Vendeur</TableHead><TableHead>Catégorie</TableHead><TableHead>Prix</TableHead><TableHead>Statut</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(p => <TableRow key={p.id}><TableCell className="font-medium">{p.name}</TableCell><TableCell>{p.vendorName}</TableCell><TableCell>{p.category}</TableCell><TableCell>{p.price.toLocaleString("fr-FR")} XOF</TableCell><TableCell><Badge variant="outline">{p.status}</Badge></TableCell><TableCell className="space-x-1"><Button size="sm" onClick={() => update(p.id, "APPROVED")}>Approuver</Button><Button size="sm" variant="outline" onClick={() => update(p.id, "REJECTED")}>Refuser</Button><Button size="sm" variant="destructive" onClick={() => update(p.id, "HIDDEN")}>Masquer</Button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length && <Empty text="Aucun produit correspondant." />}</CollectionFrame>;
}
export function AdminOrdersPage() { const [items, setItems] = useState<AdminOrder[]>([]); const [query, setQuery] = useState(""); useEffect(() => { adminOrderService.list().then(setItems); }, []); const filtered = items.filter(o => `${o.orderNumber} ${o.vendorName} ${o.customerName}`.toLowerCase().includes(query.toLowerCase())); return <CollectionFrame title="Commandes globales" description="Supervisez les flux sans remplacer le workflow vendeur."><Filters query={query} setQuery={setQuery} placeholder="Rechercher une commande, client ou vendeur" /><Table><TableHeader><TableRow><TableHead>Commande</TableHead><TableHead>Client</TableHead><TableHead>Vendeur</TableHead><TableHead>Montant</TableHead><TableHead>Statut</TableHead><TableHead>Paiement</TableHead></TableRow></TableHeader><TableBody>{filtered.map(o => <TableRow key={o.id}><TableCell className="font-medium">{o.orderNumber}</TableCell><TableCell>{o.customerName}</TableCell><TableCell>{o.vendorName}</TableCell><TableCell>{o.total.toLocaleString("fr-FR")} {o.currency}</TableCell><TableCell><Badge variant="outline">{o.status}</Badge></TableCell><TableCell>{o.paymentStatus}</TableCell></TableRow>)}</TableBody></Table>{!filtered.length && <Empty text="Aucune commande correspondant." />}</CollectionFrame>; }
export function AdminUsersPage() { const [items, setItems] = useState<AdminUser[]>([]); const [query, setQuery] = useState(""); useEffect(() => { adminUserService.list().then(setItems); }, []); const toggle = async (u: AdminUser) => { const updated = await adminUserService.setActive(u.id, u.status !== "ACTIVE"); setItems(current => current.map(item => item.id === u.id ? { ...item, ...updated, status: u.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" } : item)); }; const filtered = items.filter(u => `${u.name} ${u.email} ${u.role}`.toLowerCase().includes(query.toLowerCase())); return <CollectionFrame title="Utilisateurs" description="Clients, vendeurs et administrateurs de la plateforme."><Filters query={query} setQuery={setQuery} placeholder="Rechercher un utilisateur" /><Table><TableHeader><TableRow><TableHead>Nom</TableHead><TableHead>Email</TableHead><TableHead>Rôle</TableHead><TableHead>Statut</TableHead><TableHead>Dernière activité</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{filtered.map(u => <TableRow key={u.id}><TableCell className="font-medium">{u.name}</TableCell><TableCell>{u.email}</TableCell><TableCell>{u.role}</TableCell><TableCell><Badge variant={u.status === "ACTIVE" ? "secondary" : "destructive"}>{u.status}</Badge></TableCell><TableCell>{u.lastActivity || "—"}</TableCell><TableCell><Button size="sm" variant="outline" onClick={() => toggle(u)}>{u.status === "ACTIVE" ? "Désactiver" : "Activer"}</Button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length && <Empty text="Aucun utilisateur correspondant." />}</CollectionFrame>; }
export function AdminAuditsPage() { const [items, setItems] = useState<VendorAudit[]>([]); const [error, setError] = useState(""); useEffect(() => { adminService.getAuditHistory().then(setItems).catch(() => setError("Impossible de charger l'historique des audits.")); }, []); return <CollectionFrame title="Audits vendeurs" description="Historique des décisions d'approbation des boutiques.">{error ? <p role="alert" className="text-destructive">{error}</p> : <Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Boutique</TableHead><TableHead>Action</TableHead><TableHead>Motif</TableHead></TableRow></TableHeader><TableBody>{items.map(item => <TableRow key={item.id}><TableCell>{new Date(item.createdAt).toLocaleString("fr-FR")}</TableCell><TableCell>{item.vendorName || `Vendeur #${item.vendorId}`}</TableCell><TableCell><Badge variant="outline">{item.action.toUpperCase()}</Badge></TableCell><TableCell>{item.reason || "—"}</TableCell></TableRow>)}</TableBody></Table>}</CollectionFrame>; }
function Filters({ query, setQuery, placeholder }: { query: string; setQuery: (v: string) => void; placeholder: string }) { return <div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={e => setQuery(e.target.value)} placeholder={placeholder} /></div>; }
function CollectionFrame({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><p className="text-sm text-muted-foreground">{description}</p></CardHeader><CardContent className="space-y-4">{children}</CardContent></Card>; }
